services:
  mysql:
    ports: []
    logging:
      options:
        max-size: "20m"
        max-file: "5"

  redis:
    ports: []
    logging:
      options:
        max-size: "20m"
        max-file: "5"

  backend:
    environment:
      NODE_ENV: production
    logging:
      options:
        max-size: "20m"
        max-file: "5"

  frontend:
    logging:
      options:
        max-size: "20m"
        max-file: "5"
